#include "CNLIB/Includes.h"
#include <comutil.h>
#include <time.h>
#include <netfw.h>
#include <windowsx.h>
#include <Shlwapi.h>
#include <d3d9.h>
#include <assert.h>
#include <queue>
#include <sstream>